#!/bin/bash

CLUSTER_NAME=banana

DEV_NEXTCLOUD_MARIADB_ROOT_PASSWORD="root_pass_banana"
DEV_NEXTCLOUD_MARIADB_REPLICATION_PASSWORD="replication_pass_banana"
DEV_NEXTCLOUD_MARIADB_PASSWORD="pass_banana"

DEV_NEXTCLOUD_PASSWORD="banana"
DEV_NEXTCLOUD_TOKEN="BaNaNa"
DEV_NEXTCLOUD_USERNAME="banana"
