apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: nextcloud-mariadb-pv
  storageClassName: standard
