ingress:
  enabled: false

phpClientHttpsFix:
  enabled: true
  protocol: https

nextcloud:
  host: intra.localhost

  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    tokenKey: nextcloud-token

internalDatabase:
  enabled: false
  name: nextcloud

##
## External database configuration
##
externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: mysql

  ## Database host
  host: "nextcloud-mariadb:3306"

  ## Database user
  user: root

  ## Database password
  password: ""

  ## Database name
  database: my_database

  ## Use a existing secret
  existingSecret:
    enabled: true
    secretName: nextcloud-mariadb-secrets
    usernameKey: mariadb-root-user
    passwordKey: mariadb-root-password
    # hostKey: db-hostname-or-ip
    # databaseKey: db-name

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  # Nextcloud Data (/var/www/html)
  enabled: true
  existingClaim: "nextcloud-pvc"
